/**
 * Pure socket editing math for the Ships viewport.
 *
 * The subset of the retired `socketOps` module the viewport actually needs:
 * moving, duplicating and deleting one socket. Everything heavier (accepts
 * lists, emitter bindings, curves, default fitting) is now generated by
 * `SchemaFormGen` from the ship schema itself, so it has no hand-written
 * counterpart here — the context panel deep-links to that form instead.
 *
 * As with the arena ops, every function clones and returns; the caller hands the
 * result to `DraftPackStore.setFile`.
 */

import { hardpointsOf, type ShipConfig, type SocketConfig } from "@space-arena/shared";

export type SocketKind = SocketConfig["kind"];

/** Every socket id currently used by a ship. */
function socketIds(ship: ShipConfig): Set<string> {
  return new Set(ship.sockets.map((socket) => socket.id));
}

/**
 * A unique socket id derived from `base`: `base` if free, else `base-2`,
 * `base-3`, … (deterministic, so a duplicate is reproducible in a test).
 */
export function uniqueSocketId(existing: Set<string>, base: string): string {
  if (!existing.has(base)) return base;
  let n = 2;
  while (existing.has(`${base}-${n}`)) n++;
  return `${base}-${n}`;
}

/**
 * The 0-based FITTED-SLOT index of the socket at array position `arrayIndex`, or
 * -1 when that socket takes no fitting.
 *
 * Both `hardpoint` and `internal` sockets share one positional index space (see
 * `hardpointsOf`), and `defaultFitting` is indexed by it — so counting only
 * `kind: "hardpoint"` (as the pre-internals editor did) would mis-align every
 * fitting on a hull with a systems bay.
 */
export function fittedSlotIndexOf(ship: ShipConfig, arrayIndex: number): number {
  const socket = ship.sockets[arrayIndex];
  if (!socket || (socket.kind !== "hardpoint" && socket.kind !== "internal")) return -1;
  let slot = -1;
  for (let i = 0; i <= arrayIndex; i++) {
    const kind = ship.sockets[i]?.kind;
    if (kind === "hardpoint" || kind === "internal") slot++;
  }
  return slot;
}

/** Human label for a socket: fitted slot number for fittables, bare id otherwise. */
export function socketLabel(ship: ShipConfig, arrayIndex: number): string {
  const socket = ship.sockets[arrayIndex];
  if (!socket) return `socket #${arrayIndex}`;
  const slot = fittedSlotIndexOf(ship, arrayIndex);
  return slot >= 0 ? `#${slot} ${socket.id}` : socket.id;
}

/**
 * Insert a copy of the socket at `arrayIndex` right after it, with a unique id.
 * Duplicating a fittable socket shifts every later fitted-slot index by one, so
 * the positional `defaultFitting` is patched to keep each remaining slot's
 * module aligned (the duplicate inherits the original's default module, if any).
 */
export function duplicateSocket(ship: ShipConfig, arrayIndex: number): ShipConfig {
  const source = ship.sockets[arrayIndex];
  if (!source) return ship;
  const next = structuredClone(ship);
  const copy = structuredClone(source);
  copy.id = uniqueSocketId(socketIds(ship), `${source.id}-copy`);
  next.sockets.splice(arrayIndex + 1, 0, copy);
  const slot = fittedSlotIndexOf(ship, arrayIndex);
  if (slot >= 0 && slot < next.defaultFitting.length) next.defaultFitting.splice(slot + 1, 0, next.defaultFitting[slot]!);
  return next;
}

/**
 * Remove the socket at `arrayIndex`, dropping its positional `defaultFitting`
 * entry so the later slots keep their modules.
 *
 * A ship schema requires at least one `hardpoint`, so deleting the last one is
 * refused here rather than left to be rejected as a whole-pack blocker: the
 * draft would otherwise go invalid on a single click in the viewport.
 */
export function deleteSocket(ship: ShipConfig, arrayIndex: number): ShipConfig {
  const source = ship.sockets[arrayIndex];
  if (!source) return ship;
  if (source.kind === "hardpoint" && ship.sockets.filter((socket) => socket.kind === "hardpoint").length <= 1) return ship;
  const next = structuredClone(ship);
  next.sockets.splice(arrayIndex, 1);
  const slot = fittedSlotIndexOf(ship, arrayIndex);
  if (slot >= 0 && slot < next.defaultFitting.length) next.defaultFitting.splice(slot, 1);
  return next;
}

/** Whether {@link deleteSocket} would actually remove something. */
export function canDeleteSocket(ship: ShipConfig, arrayIndex: number): boolean {
  const socket = ship.sockets[arrayIndex];
  if (!socket) return false;
  return socket.kind !== "hardpoint" || ship.sockets.filter((other) => other.kind === "hardpoint").length > 1;
}

/**
 * Write a socket's pose. Optional members are omitted rather than written as
 * defaults, so a socket that never authored `rot`/`scale` does not gain them
 * (and therefore does not dirty the draft) just by being selected.
 */
export function setSocketTransform(
  ship: ShipConfig,
  arrayIndex: number,
  transform: { pos: [number, number, number]; rot?: [number, number, number]; scale?: number },
): ShipConfig {
  const next = structuredClone(ship);
  const socket = next.sockets[arrayIndex];
  if (socket) {
    socket.transform = {
      pos: transform.pos,
      ...(transform.rot && transform.rot.some((value) => value !== 0) ? { rot: transform.rot } : {}),
      ...(transform.scale !== undefined && transform.scale !== 1 ? { scale: transform.scale } : {}),
    };
  }
  return next;
}

/** Trim Babylon's float32 marker round-trip noise before it reaches content JSON. */
export function roundMarkerValue(value: number): number {
  return Number(value.toFixed(4));
}

/** Fitted-slot count, for the context panel's summary line. */
export function fittedSlotCount(ship: ShipConfig): number {
  return hardpointsOf(ship).length;
}
